# ============================================================================
# Titan HPC — slurm.conf
# Generated by Terraform. Do not edit by hand on nodes; change the template.
# ============================================================================

ClusterName=${cluster_name}
SlurmctldHost=${control_machine}

# ----------------------------------------------------------------------------
# Authentication and accounting
# ----------------------------------------------------------------------------
AuthType=auth/munge
CredType=cred/munge
MpiDefault=none

# ----------------------------------------------------------------------------
# Core scheduler
# ----------------------------------------------------------------------------
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory

# ----------------------------------------------------------------------------
# GRES — GPUs. AutoDetect=nvml lives in gres.conf on each compute node.
# ----------------------------------------------------------------------------
GresTypes=gpu
AccountingStorageTRES=${gres_tres}

# ----------------------------------------------------------------------------
# Accounting via slurmdbd → Aurora MySQL
# ----------------------------------------------------------------------------
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=localhost
AccountingStoragePort=6819
AccountingStorageEnforce=associations,limits,qos
JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=30

# ----------------------------------------------------------------------------
# Fair-share — prevent one user from monopolizing H100s
# ----------------------------------------------------------------------------
PriorityType=priority/multifactor
PriorityWeightFairshare=10000
PriorityWeightAge=1000
PriorityWeightJobSize=100
PriorityDecayHalfLife=7-0
PriorityFavorSmall=NO

# ----------------------------------------------------------------------------
# Power save — the autoscale hook.
# ResumeProgram launches EC2 instances; SuspendProgram terminates them.
# Per-partition SuspendTime is set by overrides below; this is the default.
# ----------------------------------------------------------------------------
SuspendProgram=/opt/titan-hpc/bin/suspend-node.sh
ResumeProgram=/opt/titan-hpc/bin/resume-node.sh
# Global fallback values — per-partition overrides in the Partitions section below
# take precedence for all defined GPU families.
SuspendTimeout=180
ResumeTimeout=1800
SuspendTime=300
SuspendExcNodes=
ResumeRate=0
SuspendRate=0
TreeWidth=65536

# ----------------------------------------------------------------------------
# Logging
# ----------------------------------------------------------------------------
SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmdPidFile=/var/run/slurm/slurmd.pid
SlurmdSpoolDir=/var/spool/slurmd
StateSaveLocation=/var/spool/slurmctld

# ----------------------------------------------------------------------------
# Timeouts, limits
# ----------------------------------------------------------------------------
SlurmctldTimeout=120
SlurmdTimeout=300
InactiveLimit=0
KillWait=30
MinJobAge=300
Waittime=0
ReturnToService=2

# ----------------------------------------------------------------------------
# Nodes — generated from gpu_family_spec
# ----------------------------------------------------------------------------
${slurm_nodes}

# ----------------------------------------------------------------------------
# Partitions — one per GPU family
# ----------------------------------------------------------------------------
${slurm_partitions}
