variable "namespace" {}
variable "env" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "security_group_id" {}
variable "iam_instance_profile" {}
variable "key_name" {}
variable "aws_region" {}
variable "max_compute_nodes" {}
variable "head_node_private_ip" {}
